name: 🗓️ New Event
description: Form to request the creation of an event.
title: "[EVENT REQ] <title>"
labels: [event request]
assignees: hec7orci7o, ZenithGD
body:
  - type: markdown
    attributes:
      value: |
        ### Contact Information
        Please provide your contact details so we can reach out regarding your event request.

  - type: input
    id: publisherName
    attributes:
      label: Publisher Name
      description: Enter the name of the person or organization hosting the event.
      placeholder: e.g., John Doe or XYZ Corp
    validations:
      required: true

  - type: input
    id: publisherEmail
    attributes:
      label: Publisher Email
      description: Enter the email address for the main contact regarding this event.
      placeholder: e.g., john.doe@example.com
    validations:
      required: true
      format: email

  - type: input
    id: publisherLinkedin
    attributes:
      label: Publisher LinkedIn
      description: Provide the LinkedIn profile ID of the publisher for professional verification.
      placeholder: e.g., https://www.linkedin.com/in/johndoe (just the last part: johndoe)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Event Details
        Please fill in the specifics about the event you’re planning.

  - type: input
    id: title
    attributes:
      label: Event Title
      description: What’s the official name of the event?
      placeholder: e.g., Unicode 2024
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Event Description
      description: Describe the event, including its purpose and what attendees can expect.
      placeholder: Share what your event is about and any key highlights.
    validations:
      required: true

  - type: input
    id: banner
    attributes:
      label: Event Banner
      description: Optionally, you can add a banner image for your event. Please provide a URL.
      placeholder: e.g., https://unsplash.com/...
    validations:
      required: false

  - type: dropdown
    id: visibility
    attributes:
      label: Event Visibility
      description: Is this event open to the public or restricted to certain attendees?
      options:
        - Public
        - Private
      default: 0
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Event Type
      description: What type of event is this?
      options:
        - Workshop
        - Hackathon
        - Datathon
        - Ideathon
        - Capture The Flag (CTF)
      default: 0
    validations:
      required: true

  - type: input
    id: challenges
    attributes:
      label: Number of Challenges
      description: How many challenges will participants face during the event?
      placeholder: e.g., 3
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Event Location
      description: Will the event be in-person or online? Please specify the venue or platform.
      placeholder: e.g., EINA, Zaragoza, ES or Online via Zoom
    validations:
      required: true

  - type: input
    id: startDate
    attributes:
      label: Start Date & Time
      description: When does the event start? Please provide the date and time.
      placeholder: e.g., yyyy-mm-dd hh:mm:ss
    validations:
      required: true

  - type: input
    id: endDate
    attributes:
      label: End Date & Time
      description: When does the event end? Please provide the date and time.
      placeholder: e.g., yyyy-mm-dd hh:mm:ss
    validations:
      required: true

  - type: input
    id: prizes
    attributes:
      label: Prizes
      description: What prizes will be awarded to participants? Please list them clearly.
      placeholder: A bullet list is preferable
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Codelab
        Thank you for providing the details of your event request. If you have any questions or need further assistance, feel free to contact us at [codelabzgz@unizar.es](mailto:codelabzgz@unizar.es).

        **Relevant Links:**
        - [LinkedIn](https://www.linkedin.com/company/codelabzgz)
        - [Help Center](https://discord.gg/eAMGGMj3XW)
        - [Terms of Service](https://codelabzgz.dev/terms)
        - [Privacy Policy](https://codelabzgz.dev/privacy)
