name: 💼 New Job Offer
description: Form to request the publication of a job offer.
title: "[JOB OFFER REQ] <title>"
labels: [job offer request]
assignees: [hec7orci7o, ZenithGD]
body:
  - type: markdown
    attributes:
      value: |
        ### Contact Information
        Please provide your contact details to help us connect with you regarding this job offer request.

  - type: input
    id: recruiterName
    attributes:
      label: Recruiter Name
      description: Enter the name of the recruiter or organization posting the job offer.
      placeholder: e.g., John Doe or XYZ Corp
    validations:
      required: true

  - type: input
    id: recruiterEmail
    attributes:
      label: Recruiter Email
      description: Please provide the email address for the primary contact regarding this job.
      placeholder: e.g., john.doe@example.com
    validations:
      required: true
      format: email

  - type: input
    id: recruiterLinkedin
    attributes:
      label: Recruiter LinkedIn
      description: Enter the LinkedIn profile ID for the recruiter or organization posting the job.
      placeholder: e.g., johndoe
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Job Offer Details
        Please provide detailed information about the job position being offered.

  - type: input
    id: jobTitle
    attributes:
      label: Job Title
      description: What is the official title of the job position?
      placeholder: e.g., Senior Software Engineer
    validations:
      required: true

  - type: textarea
    id: jobDescription
    attributes:
      label: Job Description
      description: Outline the key responsibilities and requirements for this position.
      placeholder: Describe what you’re looking for in a candidate.
    validations:
      required: true

  - type: input
    id: company
    attributes:
      label: Company Name
      description: What is the name of the company offering this position?
      placeholder: e.g., XYZ Corp
    validations:
      required: true

  - type: dropdown
    id: jobType
    attributes:
      label: Job Type
      description: What type of employment is being offered?
      options:
        - Full-time
        - Part-time
        - Contract
        - Internship
        - Freelance
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: otherJobType
    attributes:
      label: Other Job Type (if selected)
      description: If you selected "Other," please specify the type of job.
      placeholder: e.g., Consultant
    validations:
      required: false

  - type: dropdown
    id: jobLocationType
    attributes:
      label: Work Environment
      description: Is this job remote, on-site, or a hybrid arrangement?
      options:
        - Remote
        - On-site
        - Hybrid
      default: 0
    validations:
      required: true

  - type: input
    id: jobLocation
    attributes:
      label: Job Location
      description: If the job is on-site or hybrid, please provide the physical location.
      placeholder: e.g., New York, NY
    validations:
      required: false

  - type: dropdown
    id: experienceLevel
    attributes:
      label: Experience Required
      description: What level of experience is necessary for this role?
      options:
        - No experience
        - Junior (< 2 years)
        - Mid-level (2-5 years)
        - Senior (> 5 years)
        - Not specified
      default: 3
    validations:
      required: true

  - type: input
    id: salary
    attributes:
      label: Salary Range
      description: Please specify the salary range for this position. Note that, as per [DOUE-L-2023-80668](https://www.boe.es/buscar/doc.php?id=DOUE-L-2023-80668), the salary range cannot be left blank after 2026.
      placeholder: e.g., $60,000 - $80,000 per year
    validations:
      required: true

  - type: textarea
    id: responsibilities
    attributes:
      label: Candidate Responsibilities
      description: What tasks will the candidate be expected to perform upon starting the job?
      placeholder: Please provide a bullet list.
    validations:
      required: true

  - type: textarea
    id: desirable
    attributes:
      label: Desired Skills
      description: What skills should the ideal candidate possess?
      placeholder: A bullet list is preferred.
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits for the New Employee
      description: What unique benefits does your offer include that might attract candidates?
      placeholder: A bullet list is fine.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Application Details
        Please provide information on how candidates can apply.

  - type: input
    id: applicationDeadline
    attributes:
      label: Application Deadline
      description: What is the last date for candidates to submit their applications?
      placeholder: e.g., yyyy-mm-dd
    validations:
      required: true

  - type: input
    id: applicationLink
    attributes:
      label: Application Link
      description: Provide a link for candidates to apply for this position.
      placeholder: e.g., https://www.linkedin.com/jobs/view/1234567890
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Codelab
        Thank you for providing the details of your job offer. If you have any questions or need further assistance, please contact us at [codelabzgz@unizar.es](mailto:codelabzgz@unizar.es).

        **Relevant Links:**
        - [LinkedIn](https://www.linkedin.com/company/codelabzgz)
        - [Help Center](https://discord.gg/eAMGGMj3XW)
        - [Terms of Service](https://codelabzgz.dev/terms)
        - [Privacy Policy](https://codelabzgz.dev/privacy)
