blank_issues_enabled: false
contact_links:
  - name: Codelab Community Support
    url: https://discord.gg/eAMGGMj3XW
    about: Please ask and answer questions in our community Discord server.
  - name: Codelab Website
    url: https://codelabzgz.dev
    about: Visit our official website for more information.
