blank_issues_enabled: false
contact_links:
  - name: Codelab Community Support
    url: https://discord.gg/eAMGGMj3XW
    about: Please ask and answer questions in our community Discord server.
  - name: Codelab Privacy Policy
    url: https://codelabzgz.dev/privacy
    about: Review our privacy policy here.
  - name: Codelab Terms of Service
    url: https://codelabzgz.dev/terms
    about: Read our terms of service here.
  - name: Codelab Website
    url: https://codelabzgz.dev
    about: Visit our official website for more information.
  - name: Codelab Email Contact
    url: mailto:codelabzgz@unizar.es
    about: Contact us via email for additional support or inquiries.
