name: 💼 New Job Offer
description: Form to request the publication of a job offer
title: "[JOB OFFER REQ] <title>"
labels: [job offer request]
assignees: hec7orci7o, ZenithGD
body:
  - type: markdown
    attributes:
      value: |
        ### Contact Information
        Please provide the following details to help us get in touch with you regarding this job offer request.

  - type: input
    id: recruiterName
    attributes:
      label: Recruiter Name
      description: Enter the name of the recruiter or organization publishing the job offer.
      placeholder: e.g., John Doe or XYZ Corp
    validations:
      required: true

  - type: input
    id: recruiterEmail
    attributes:
      label: Recruiter Email
      description: Enter the email address of the recruiter for contact purposes.
      placeholder: e.g., john.doe@example.com
    validations:
      required: true
      format: email

  - type: markdown
    attributes:
      value: |
        ### Job Offer Details
        Please provide detailed information about the job offer.

  - type: input
    id: jobTitle
    attributes:
      label: Job Title
      description: What is the title of the job position?
      placeholder: e.g., Senior Software Engineer
    validations:
      required: true

  - type: input
    id: company
    attributes:
      label: Company Name
      description: Enter the name of the company offering the position.
      placeholder: e.g., XYZ Corp
    validations:
      required: true

  - type: dropdown
    id: jobType
    attributes:
      label: Job Type
      description: What type of job is this?
      options:
        - Full-time
        - Part-time
        - Contract
        - Internship
        - Freelance
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: otherJobType
    attributes:
      label: Other Job Type (if selected)
      description: If you selected "Other" above, please specify the type of job.
      placeholder: e.g., Consultant
    validations:
      required: false
      conditional: jobType == 'Other'

  - type: dropdown
    id: jobLocationType
    attributes:
      label: Work Environment
      description: Is the job remote, on-site, or hybrid?
      options:
        - Remote
        - On-site
        - Hybrid
      default: 0
    validations:
      required: true

  - type: input
    id: jobLocation
    attributes:
      label: Job Location
      description: If the job is on-site or hybrid, where is the physical location?
      placeholder: e.g., New York, NY
    validations:
      required: false

  - type: dropdown
    id: experienceLevel
    attributes:
      label: Experience Required
      description: What level of experience is required for this job?
      options:
        - Junior (< 2 years)
        - Mid-level (2-5 years)
        - Senior (> 5 years)
        - Not specified
      default: 3
    validations:
      required: true

  - type: input
    id: salary
    attributes:
      label: Salary (optional)
      description: Specify the salary range or leave blank if not disclosed.
      placeholder: e.g., $60,000 - $80,000 per year
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Application Details
        Provide information regarding the application process.

  - type: input
    id: applicationDeadline
    attributes:
      label: Application Deadline
      description: What is the deadline to apply for the job?
      placeholder: e.g., yyyy-mm-dd
    validations:
      required: true

  - type: input
    id: applicationLink
    attributes:
      label: Application Link
      description: Provide a link where candidates can apply for the position.
      placeholder: e.g., https://www.linkedin.com/jobs/view/1234567890
    validations:
      required: true

  - type: input
    id: alternateApplicationLink
    attributes:
      label: Alternate Application Link
      description: Provide an alternate link if the primary link is unavailable or not working.
      placeholder: e.g., https://company.com/careers/apply
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Codelab
        Thank you for providing the details of your job offer. If you have any questions or need further assistance, please contact us at [codelabzgz@unizar.es](mailto:codelabzgz@unizar.es).

        **Relevant Links:**
        - [LinkedIn](https://www.linkedin.com/company/codelabzgz)
        - [Help Center](https://discord.gg/eAMGGMj3XW)
        - [Terms of Service](https://codelabzgz.dev/terms)
        - [Privacy Policy](https://codelabzgz.dev/privacy)
